[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit BusIO @^1.17.4
    adafruit/Adafruit seesaw Library@^1.7.9
    olikraus/U8g2@^2.36.17
	seeed-studio/Grove - LCD RGB Backlight @^1.0.2